#!/bin/bash
echo "It is a period of civil war. Rebel spaceships, striking 
from a hidden base, have won their first victory against the 
evil Galactic Empire." echo "During the battle, Rebel spies 
managed to steal secret plans to the Empire's ultimate weapon, 
the DEATH STAR, an armored space station with enough power to 
destroy an entire planet." echo "Pursued by the Empire's 
sinister agents, Princess Leia races home aboard her starship, 
custodian of the stolen plans that can save her people and 
restore freedom to the galaxy..." 

echo
echo "Scene 1" 
echo
echo "Captain Antilles: 'Hold your fire! Hold your fire! Stand to! 
Direct hit!'" echo "Darth Vader: 'I find your lack of faith 
disturbing.'" echo echo "Stormtroopers enter and capture the 
Rebel crew" echo echo "Captain Antilles: 'We've got to give the 
plans to the Rebel Alliance.'"
